#!/bin/sh
# rsync wrapper that sets configs based on environment variables
# Adapted from https://github.com/axiom-data-science/rsync-server/blob/master/entrypoint.sh

set -e
USERNAME=${USERNAME:-user}
PASSWORD=${PASSWORD:-pass}
ALLOW=${ALLOW:-192.168.8.0/24 192.168.24.0/24 172.16.0.0/12 127.0.0.1/32}
VOLUME=${VOLUME:-data}

# Setup rsync config files
echo "$USERNAME:$PASSWORD" > /etc/rsyncd.secrets
chmod 0400 /etc/rsyncd.secrets
cat > /etc/rsyncd.conf <<EOF
pid file = /var/run/rsyncd.pid
log file = /dev/stdout
timeout = 300
max connections = 10
port = 873

[${VOLUME}]
	uid = root
	gid = root
	fake super = true
	hosts deny = *
	hosts allow = ${ALLOW}
	read only = false
	path = /data
	comment = ${VOLUME} directory
	auth users = ${USERNAME}
	secrets file = /etc/rsyncd.secrets
EOF

# Execute rsync
exec /usr/bin/rsync --no-detach --daemon --config /etc/rsyncd.conf "$@"

